### ISSUE TITLE
gorm 获取gin context 的traceId

### ISSUE THREAD

**Issue by GreenAppleOne** [axiaoxin-com/logging#20]
目前grom 想使用traceId 必须要增加参数才能传递过来，这样对业务入侵改造太大了，怎么能友好的获取每个请求的traceId呢？谢谢

**Comment by axiaoxin** [comment]
gorm取traceid看起来好像都要侵入业务代码，之前使用老版本时获取traceid是采用一行代码来覆盖原有db对象实现的 https://github.com/axiaoxin-com/logging/blob/3c923343666b0960dfece66f6555d2b41932316e/example/gorm.go#L53  不知道是否有帮助
