### ISSUE TITLE
使用"带 Trace ID 的 CtxLogger"的同时将日志记录到文件，并实现定时切割

### ISSUE THREAD

**Issue by zgli2011** [axiaoxin-com/logging#21]
在使用"带 Trace ID 的 CtxLogger"的同时将日志记录到文件，实现日志的定时切割
options := logging.Options{
	LumberjackSink: sink,
	OutputPaths:    []string{"lumberjack:"},
}
这个配置怎么生效

**Comment by axiaoxin** [comment]
https://github.com/axiaoxin-com/logging/blob/master/example/lumberjack.go#L9 参考下这里

**Comment by zgli2011** [comment]
> https://github.com/axiaoxin-com/logging/blob/master/example/lumberjack.go#L9 参考下这里

这个样例我知道，我的疑问就在这边产生的。我定义了option之后，在logging的方法中没有找到将定义的option应用到现有logger中。
`	options := logging.Options{
		LumberjackSink: logging.NewLumberjackSink("lumberjack", log_file, 7, 30, 1, true, true),
		OutputPaths:    []string{"lumberjack:"},
	}
	logger, _ := logging.NewLogger(options)
	// 替换默认 logger
	logging.ReplaceLogger(logger)
	logging.GinLoggerWithConfig(logging.GinLoggerConfig{
		TraceIDFunc: getTraceID,
	})

	return func(c *gin.Context) {
		c.Next()
	}`

**Comment by axiaoxin** [comment]
logging.ReplaceLogger(logger) 这里把logging里用的默认logger替换了
