### ISSUE TITLE
gin的请求日志能不能在方法的最开始

### ISSUE THREAD

**Issue by zundaren** [axiaoxin-com/logging#22]
![image](https://user-images.githubusercontent.com/44863479/164891235-fa9d1b8f-807d-464b-beec-b46b032c80b1.png)
等到方法结束打印这个时间不好定位问题，还要根据执行了多长长时间反推

**Comment by zundaren** [comment]
执行时间希望再后面加个单位

**Comment by axiaoxin** [comment]
在最开始的话不能打印请求耗时和返回体相关的信息。
执行时间`latency`字段已改为`latency_seconds`

**Comment by zundaren** [comment]
> 在最开始的话不能打印请求耗时和返回体相关的信息。 执行时间`latency`字段已改为`latency_seconds`

要么就在加个打印字段，请求进入的起始时间
或者方法入口打印请求相关内容和结束打印执行时间和结果 ，怎么样

**Comment by axiaoxin** [comment]
v1.2.15 默认加上了`req_time`字段记录起始时间

**Comment by zundaren** [comment]
赞
